#
# Copyright IBM Corporation 2020,2021
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

apiVersion: apps/v1
kind: Deployment
metadata:
  name: reefer-actors
  labels:
    name: reefer-actors
spec:
  replicas: {{ .Values.reefer.actors.replicas }}
  selector:
    matchLabels:
      name: reefer-actors
  template:
    metadata:
      labels:
        name: reefer-actors
      annotations:
        kar.ibm.com/app: reefer
        kar.ibm.com/actors: order,reefer,voyage
        kar.ibm.com/verbose: {{ .Values.kar.verbose }}
        kar.ibm.com/appPort: {{ .Values.reefer.actors.port | quote }}
    spec:
{{- if .Values.global.affinity }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kar-type
                operator: In
                values:
                - worker
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: name
                  operator: In
                  values:
                  - reefer-actors
              topologyKey: "kubernetes.io/hostname"
{{- end }}
      imagePullSecrets:
         - name: {{ .Values.kar.imagePullSecret }}
      containers:
      - name: app
        image: {{ .Values.kar.imagePrefix }}/{{ .Values.reefer.actors.imageName }}
        ports:
        - name: app
          containerPort: {{ .Values.reefer.actors.port }}
