apiVersion: v1
kind: Service
metadata:
  name: reefer-frontend
  labels:
    name: reefer-frontend
spec:
  selector:
    name: reefer-frontend
  ports:
    - name: app
      port: {{ .Values.reefer.frontend.port }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reefer-frontend
  labels:
    name: reefer-frontend
spec:
  replicas: {{ .Values.reefer.frontend.replicas }}
  selector:
    matchLabels:
      name: reefer-frontend
  template:
    metadata:
      labels:
        name: reefer-frontend
    spec:
      imagePullSecrets:
        - name: {{ .Values.kar.imagePullSecret }}
      containers:
      - name: app
        image: {{ .Values.reefer.frontend.image }}
        command: [ "/bin/bash", "-c", "/kar/bin/fe-start.sh" ]
        ports:
        - name: app
          containerPort: {{ .Values.reefer.frontend.port }}
        env:
        - name: REST_URL
          value: https://reefer-rest.{{ .Values.ingress.subdomain }}
