#
# Copyright IBM Corporation 2020,2021
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

apiVersion: apps/v1
kind: Deployment
metadata:
  name: reefer-monitor
  labels:
    name: reefer-monitor
spec:
  replicas: {{ .Values.reefer.monitor.replicas }}
  selector:
    matchLabels:
      name: reefer-monitor
  template:
    metadata:
      labels:
        name: reefer-monitor
      annotations:
        kar.ibm.com/app: reefer
        kar.ibm.com/verbose: {{ .Values.kar.verbose }}
        kar.ibm.com/appPort: {{ .Values.reefer.monitor.port | quote }}
    spec:
      imagePullSecrets:
         - name: {{ .Values.kar.imagePullSecret }}
      volumes:
      - name: runtime-config
        secret:
          secretName: kar.ibm.com.runtime-config
      containers:
      - name: app
        image: {{ .Values.kar.imageRegistry }}{{ .Values.reefer.monitor.imageName }}
        ports:
        - name: app
          containerPort: {{ .Values.reefer.monitor.port }}
        volumeMounts:
        - mountPath: /var/run/secrets/kar.ibm.com
          name: runtime-config
          readOnly: true
        env:
        - name: ORDERSTATS_DELAY
          value: {{ .Values.reefer.monitor.delay | quote }}
        - name: ORDERSTATS_THRESHOLD
          value: {{ .Values.reefer.monitor.threshold | quote }}
        - name: ORDERSTATS_RESET
          value: {{ .Values.reefer.monitor.reset | quote }}
