version: "3"
services:
  rest:
    image: us.icr.io/research/kar-dev/reefer/reefer-rest
    ports:
      - "9080:9080"
    network_mode: "host"
    environment:
      KAR_SIDECAR_IN_CONTAINER: "true"
      KAR_APP: reefer
      KAFKA_BROKERS:  ${KAFKA_HOST:-localhost}:${KAFKA_PORT:-31093}
      KAFKA_VERSION:  ${KAFKA_VERSION:-2.4.0}
      REDIS_HOST:     ${REDIS_HOST:-localhost}
      REDIS_PORT:     ${REDIS_PORT:-31379}
      REDIS_PASSWORD: ${REDIS_PASSWORD:-passw0rd}
      KAR_EXTRA_ARGS: -app_port 9080 -service reeferservice
    hostname: rest
  simulators:
    image: us.icr.io/research/kar-dev/reefer/simulators
    ports:
      - "7080:7080"
    network_mode: "host"
    environment:
      KAR_SIDECAR_IN_CONTAINER: "true"
      KAR_APP: reefer
      KAFKA_BROKERS:  ${KAFKA_HOST:-localhost}:${KAFKA_PORT:-31093}
      KAFKA_VERSION:  ${KAFKA_VERSION:-2.4.0}
      REDIS_HOST:     ${REDIS_HOST:-localhost}
      REDIS_PORT:     ${REDIS_PORT:-31379}
      REDIS_PASSWORD: ${REDIS_PASSWORD:-passw0rd}
      KAR_EXTRA_ARGS: -app_port 7080 -service simservice -actors simhelper
    hostname: simulators
  actors:
    image: us.icr.io/research/kar-dev/reefer/actors
    network_mode: "host"
    environment:
      KAR_SIDECAR_IN_CONTAINER: "true"
      KAR_APP: reefer
      KAFKA_BROKERS:  ${KAFKA_HOST:-localhost}:${KAFKA_PORT:-31093}
      KAFKA_VERSION:  ${KAFKA_VERSION:-2.4.0}
      REDIS_HOST:     ${REDIS_HOST:-localhost}
      REDIS_PORT:     ${REDIS_PORT:-31379}
      REDIS_PASSWORD: ${REDIS_PASSWORD:-passw0rd}
      KAR_EXTRA_ARGS: -actors order,reefer,voyage,reefer-provisioner
    hostname: actors
  frontend:
    image: us.icr.io/research/kar-dev/reefer/frontend
    ports:
      - "9088:9088"
    network_mode: "host"
    hostname: frontend
